
package org.ostenant.yoga.store.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DirMakerImplService", targetNamespace = "http://webservice.yoga-store.com/", wsdlLocation = "http://localhost:8089/picture/mkdir?wsdl")
public class DirMakerImplService
    extends Service
{

    private final static URL DIRMAKERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DIRMAKERIMPLSERVICE_EXCEPTION;
    private final static QName DIRMAKERIMPLSERVICE_QNAME = new QName("http://webservice.yoga-store.com/", "DirMakerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/picture/mkdir?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIRMAKERIMPLSERVICE_WSDL_LOCATION = url;
        DIRMAKERIMPLSERVICE_EXCEPTION = e;
    }

    public DirMakerImplService() {
        super(__getWsdlLocation(), DIRMAKERIMPLSERVICE_QNAME);
    }

    public DirMakerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIRMAKERIMPLSERVICE_QNAME, features);
    }

    public DirMakerImplService(URL wsdlLocation) {
        super(wsdlLocation, DIRMAKERIMPLSERVICE_QNAME);
    }

    public DirMakerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIRMAKERIMPLSERVICE_QNAME, features);
    }

    public DirMakerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirMakerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DirMakerImpl
     */
    @WebEndpoint(name = "DirMakerImplPort")
    public DirMakerImpl getDirMakerImplPort() {
        return super.getPort(new QName("http://webservice.yoga-store.com/", "DirMakerImplPort"), DirMakerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirMakerImpl
     */
    @WebEndpoint(name = "DirMakerImplPort")
    public DirMakerImpl getDirMakerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.yoga-store.com/", "DirMakerImplPort"), DirMakerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIRMAKERIMPLSERVICE_EXCEPTION!= null) {
            throw DIRMAKERIMPLSERVICE_EXCEPTION;
        }
        return DIRMAKERIMPLSERVICE_WSDL_LOCATION;
    }

}
